frontend:
  image: totetmatt/mediamur-frontend
  ports:
    - "8080:80"
  links:
    - backend:backend
  volumes_from:
    - mediamur-backend

    
backend:
  image: totetmatt/mediamur-backend
  ports:
    - 8080
  environment:
    TWITTER_OAUTHCONSUMERKEY:<yourOauthConsumerKey>
    TWITTER_OAUTHCONSUMERSECRET:<yourOauthConsumerSecret>
    TWITTER_OAUTHACCESSTOKEN:<yourOauthAccessToken>
    TWITTER_OAUTHACCESSTOKENSECRET:<yourOauthAccessTokenSecret>
    STREAM_WORDS:""
    STREAM_USERS:""
    STREAM_LOCATIONS:""

